name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        TARGET:
          - {
              ABI: o32
            }
          - {
              ABI: n32
            }
          - {
              ABI: o64
            }
          - {
              ABI: n64
            }

    name: Building for ABI ${{ matrix.TARGET.ABI }}
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y build-essential gcc-mips-linux-gnu

      - name: Make
        shell: bash
        run: |
          make TARGET_ABI=${{ matrix.TARGET.ABI }}

      - name: Create release archive
        shell: bash
        run: |
          cd build/${{ matrix.TARGET.ABI }}/
          tar -czf ../../libgcc_vr4300-${{ matrix.TARGET.ABI }}.tar.gz libgcc_vr4300.a
          cd ../..

      - name: Upload archive
        uses: actions/upload-artifact@v3
        with:
          name: libgcc_vr4300-${{ matrix.TARGET.ABI }}
          path: |
            libgcc_vr4300-${{ matrix.TARGET.ABI }}.tar.gz

      - name: Publish release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: libgcc_vr4300-${{ matrix.TARGET.ABI }}.tar.gz
