name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        TARGET:
          - {
            }

    name: Building
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y build-essential gcc-mips-linux-gnu

      - name: Make
        shell: bash
        run: |
          make -j $(nproc)

      - name: Upload archive
        uses: actions/upload-artifact@v3
        with:
          name: libgcc_vr4300
          path: |
            build/o32/libgcc_vr4300.a

      # - name: Publish release
      #   uses: softprops/action-gh-release@v1
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     files: ${{ matrix.TARGET.ARCHIVE_NAME }}
